# Generated by Django 5.2.1 on 2025-05-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_entregador_entrega_entregador'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue')], default='pendente', max_length=20, verbose_name='Status da Entrega'),
        ),
    ]
